CREATE TABLE IF NOT EXISTS Books (Id INTEGER PRIMARY KEY ASC, Title TEXT, Author TEXT, Year INTEGER);
INSERT INTO Books (Title, Author, Year) VALUES ('1984', 'George Orwell ', 1949);
INSERT INTO Books (Title, Author, Year) VALUES ('Earth Abides', 'George R. Stewart ', 1949);
INSERT INTO Books (Title, Author, Year) VALUES ('The Martian Chronicles', 'Ray Bradbury ', 1950);
INSERT INTO Books (Title, Author, Year) VALUES ('The Puppet Masters', 'Robert A. Heinlein ', 1951);
INSERT INTO Books (Title, Author, Year) VALUES ('The Day of the Triffids', 'John Wyndham ', 1951);
INSERT INTO Books (Title, Author, Year) VALUES ('Limbo', 'Bernard Wolfe ', 1952);
INSERT INTO Books (Title, Author, Year) VALUES ('The Demolished Man', 'Alfred Bester ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('Fahrenheit 451', 'Ray Bradbury ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('Childhood''s End', 'Arthur C. Clarke ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('The Paradox Men', 'Charles L. Harness ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('Bring the Jubilee', 'Ward Moore ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('The Space Merchants', 'Frederik Pohl and C. M. Kornbluth ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('Ring Around the Sun', 'Clifford D. Simak ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('More Than Human', 'Theodore Sturgeon ', 1953);
INSERT INTO Books (Title, Author, Year) VALUES ('Mission of Gravity', 'Hal Clement ', 1954);
INSERT INTO Books (Title, Author, Year) VALUES ('A Mirror for Observers', 'Edgar Pangborn ', 1954);
INSERT INTO Books (Title, Author, Year) VALUES ('The End of Eternity', 'Isaac Asimov ', 1955);
INSERT INTO Books (Title, Author, Year) VALUES ('The Long Tomorrow', 'Leigh Brackett ', 1955);
INSERT INTO Books (Title, Author, Year) VALUES ('The Inheritors', 'William Golding ', 1955);
INSERT INTO Books (Title, Author, Year) VALUES ('The Stars My Destination', 'Alfred Bester ', 1956);
INSERT INTO Books (Title, Author, Year) VALUES ('The Death of Grass', 'John Christopher ', 1956);
INSERT INTO Books (Title, Author, Year) VALUES ('The City and the Stars', 'Arthur C. Clarke ', 1956);
INSERT INTO Books (Title, Author, Year) VALUES ('The Door into Summer', 'Robert A. Heinlein ', 1957);
INSERT INTO Books (Title, Author, Year) VALUES ('The Midwich Cuckoos', 'John Wyndham ', 1957);
INSERT INTO Books (Title, Author, Year) VALUES ('Non-Stop', 'Brian Aldiss ', 1958);
INSERT INTO Books (Title, Author, Year) VALUES ('A Case of Conscience', 'James Blish ', 1958);
INSERT INTO Books (Title, Author, Year) VALUES ('Have Space-Suit Will Travel', 'Robert A. Heinlein ', 1958);
INSERT INTO Books (Title, Author, Year) VALUES ('Time Out of Joint', 'Philip K. Dick ', 1959);
INSERT INTO Books (Title, Author, Year) VALUES ('Alas, Babylon', 'Pat Frank ', 1959);
INSERT INTO Books (Title, Author, Year) VALUES ('A Canticle for Leibowitz', 'Walter M. Miller ', 1959);
INSERT INTO Books (Title, Author, Year) VALUES ('The Sirens of Titan', 'Kurt Vonnegut ', 1959);
INSERT INTO Books (Title, Author, Year) VALUES ('Rogue Moon', 'Algis Buldrys ', 1960);
INSERT INTO Books (Title, Author, Year) VALUES ('Venus Plus X', 'Theodore Sturgeon ', 1960);
INSERT INTO Books (Title, Author, Year) VALUES ('Hothouse', 'Brian W. Aldiss ', 1962);
INSERT INTO Books (Title, Author, Year) VALUES ('The Drowned World', 'J. G. Ballard ', 1962);
INSERT INTO Books (Title, Author, Year) VALUES ('A Clockwork Orange', 'Anthony Burgess ', 1962);
INSERT INTO Books (Title, Author, Year) VALUES ('The Man in the High Castle', 'Philip K. Dick ', 1962);
INSERT INTO Books (Title, Author, Year) VALUES ('Journey Beyond Tomorrow', 'Robert Sheckley ', 1963);
INSERT INTO Books (Title, Author, Year) VALUES ('Way Station', 'Clifford D. Simak ', 1963);
INSERT INTO Books (Title, Author, Year) VALUES ('Cat''s Cradle', 'Kurt Vonnegut ', 1963);
INSERT INTO Books (Title, Author, Year) VALUES ('Greybeard', 'Brian W. Aldiss ', 1964);
INSERT INTO Books (Title, Author, Year) VALUES ('Nova Express', 'William S. Burroughs ', 1964);
INSERT INTO Books (Title, Author, Year) VALUES ('Martian Time-Slip', 'Philip K. Dick ', 1964);
INSERT INTO Books (Title, Author, Year) VALUES ('The Three Stigmata of Palmer Eldritch', 'Philip K. Dick ', 1964);
INSERT INTO Books (Title, Author, Year) VALUES ('The Wanderer', 'Fritz Leiber ', 1964);
INSERT INTO Books (Title, Author, Year) VALUES ('Dr. Bloodmoney', 'Philip K. Dick ', 1965);
INSERT INTO Books (Title, Author, Year) VALUES ('Dune', 'Frank Herbert ', 1965);
INSERT INTO Books (Title, Author, Year) VALUES ('The Crystal World', 'J. G. Ballard ', 1966);
INSERT INTO Books (Title, Author, Year) VALUES ('Make Room! Make Room!', 'Harry Harrison ', 1966);
INSERT INTO Books (Title, Author, Year) VALUES ('Flowers for Algernon', 'Daniel Keyes ', 1966);
INSERT INTO Books (Title, Author, Year) VALUES ('The Dream Master', 'Roger Zelazny ', 1966);
INSERT INTO Books (Title, Author, Year) VALUES ('Stand on Zanzibar', 'John Brunner ', 1968);
INSERT INTO Books (Title, Author, Year) VALUES ('Nova', 'Samuel R. Delany ', 1968);
INSERT INTO Books (Title, Author, Year) VALUES ('Do Androids Dream of Electric Sheep ?', 'Philip K. Dick ', 1968);
INSERT INTO Books (Title, Author, Year) VALUES ('Camp Concentration', 'Thomas M. Disch ', 1968);
INSERT INTO Books (Title, Author, Year) VALUES ('The Final Programme', 'Michael Moorcock ', 1968);
INSERT INTO Books (Title, Author, Year) VALUES ('Pavane', 'Keith Roberts ', 1968);
INSERT INTO Books (Title, Author, Year) VALUES ('Heroes and Villains', 'Angela Carter ', 1969);
INSERT INTO Books (Title, Author, Year) VALUES ('The Left Hand of Darkness', 'Ursula K. Le Guin ', 1969);
INSERT INTO Books (Title, Author, Year) VALUES ('The Palace of Eternity', 'Bob Shaw ', 1969);
INSERT INTO Books (Title, Author, Year) VALUES ('Bug Jack Barron', 'Norman Spinard ', 1969);
INSERT INTO Books (Title, Author, Year) VALUES ('Tau Zero', 'Poul Anderson ', 1970);
INSERT INTO Books (Title, Author, Year) VALUES ('Downward to the Earth', 'Robert Silverberg ', 1970);
INSERT INTO Books (Title, Author, Year) VALUES ('The Year of the Quiet Sun', 'Wilson Tucker ', 1970);
INSERT INTO Books (Title, Author, Year) VALUES ('334', 'Thomas M. Disch ', 1972);
INSERT INTO Books (Title, Author, Year) VALUES ('The Fifth Head of Cerberus', 'Gene Wolf ', 1972);
INSERT INTO Books (Title, Author, Year) VALUES ('Crash', 'J. G. Ballard ', 1973);
INSERT INTO Books (Title, Author, Year) VALUES ('Looking Backward, From the Year 2000', 'Mack Reynolds ', 1973);
INSERT INTO Books (Title, Author, Year) VALUES ('The Embedding', 'Ian Watson ', 1973);
INSERT INTO Books (Title, Author, Year) VALUES ('Walk to the End of the World', 'Suzy Mckee Charnas ', 1974);
INSERT INTO Books (Title, Author, Year) VALUES ('The Centauri Device', 'M. John Harrison ', 1974);
INSERT INTO Books (Title, Author, Year) VALUES ('The Dispossessed', 'Ursula K. Le Guin ', 1974);
INSERT INTO Books (Title, Author, Year) VALUES ('Inverted World', 'Christopher Priest ', 1974);
INSERT INTO Books (Title, Author, Year) VALUES ('High-Rise', 'J. G. Ballard ', 1975);
INSERT INTO Books (Title, Author, Year) VALUES ('Galaxies', 'Barry N. Malzberg ', 1975);
INSERT INTO Books (Title, Author, Year) VALUES ('The Female Man', 'Joanna Russ ', 1975);
INSERT INTO Books (Title, Author, Year) VALUES ('Orbitsville', 'Bob Shaw ', 1975);
INSERT INTO Books (Title, Author, Year) VALUES ('The Alteration', 'Kingsley Amis ', 1976);
INSERT INTO Books (Title, Author, Year) VALUES ('Woman on the Edge of Time', 'Marge Piercy ', 1976);
INSERT INTO Books (Title, Author, Year) VALUES ('Man Plus', 'Fredrik Pohl ', 1976);
INSERT INTO Books (Title, Author, Year) VALUES ('Michaelmas', 'Algis Budrys ', 1977);
INSERT INTO Books (Title, Author, Year) VALUES ('The Ophiuchi Hotline', 'John Varley ', 1977);
INSERT INTO Books (Title, Author, Year) VALUES ('Miracle Visitors', 'Ian Watson ', 1978);
INSERT INTO Books (Title, Author, Year) VALUES ('Engine Summer', 'John Crowley ', 1979);
INSERT INTO Books (Title, Author, Year) VALUES ('On Wings of Song', 'Thomas M. Disch ', 1979);
INSERT INTO Books (Title, Author, Year) VALUES ('The Walking Shadow', 'Brian Stableford ', 1979);
INSERT INTO Books (Title, Author, Year) VALUES ('Juniper Time', 'Kate Wilhelm ', 1979);
INSERT INTO Books (Title, Author, Year) VALUES ('Timescape', 'Gregory Benford ', 1980);
INSERT INTO Books (Title, Author, Year) VALUES ('The Dreaming Dragons', 'Damien Broderick ', 1980);
INSERT INTO Books (Title, Author, Year) VALUES ('Wild Seed', 'Octavia A. Butler ', 1980);
INSERT INTO Books (Title, Author, Year) VALUES ('Riddley Walker', 'Russell Hoban ', 1980);
INSERT INTO Books (Title, Author, Year) VALUES ('The Unreasoning Mask', 'Philip Jose Farmer ', 1980);
INSERT INTO Books (Title, Author, Year) VALUES ('Oath of Fealty', 'Larry Niven and Jerry Pournelle ', 1981);
INSERT INTO Books (Title, Author, Year) VALUES ('No Enemy But Time', 'Michael Bishop ', 1982);
INSERT INTO Books (Title, Author, Year) VALUES ('Neuromancer', 'William Gibson ', 1984);
